substitutions:
  _REGION: africa-south1
  _PROJECT_ID: df-frontend
  _REPO: controlroom
  _IMAGE: controlroom

steps:
  # Step 1: Build the Docker image using the multi-stage Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:$COMMIT_SHA"
      - "."

# Step 2: Push the built image to Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY