// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateUser(arg1, arg2) {
  return window['go']['core']['App']['AuthenticateUser'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['core']['App']['CheckUpdate']();
}

export function DeleteContact(arg1, arg2) {
  return window['go']['core']['App']['DeleteContact'](arg1, arg2);
}

export function ExportTableToExcel(arg1) {
  return window['go']['core']['App']['ExportTableToExcel'](arg1);
}

export function GenerateMatterReference(arg1) {
  return window['go']['core']['App']['GenerateMatterReference'](arg1);
}

export function GetContacts(arg1) {
  return window['go']['core']['App']['GetContacts'](arg1);
}

export function GetLastUsername() {
  return window['go']['core']['App']['GetLastUsername']();
}

export function PerformUpdate(arg1) {
  return window['go']['core']['App']['PerformUpdate'](arg1);
}

export function RestartApp() {
  return window['go']['core']['App']['RestartApp']();
}

export function SaveContact(arg1) {
  return window['go']['core']['App']['SaveContact'](arg1);
}

export function SaveLastUsername(arg1) {
  return window['go']['core']['App']['SaveLastUsername'](arg1);
}

export function TriggerSync() {
  return window['go']['core']['App']['TriggerSync']();
}
