// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {context} from '../models';

export function AuthenticateUser(arg1:string,arg2:string):Promise<void>;

export function CheckUpdate():Promise<core.UpdateCheckResult>;

export function DeleteContact(arg1:string,arg2:string):Promise<void>;

export function ExportTableToExcel(arg1:core.ExportPayload):Promise<void>;

export function GenerateMatterReference(arg1:context.Context):Promise<string>;

export function GetContacts(arg1:string):Promise<Array<core.ContactRecord>>;

export function GetLastUsername():Promise<string>;

export function PerformUpdate(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function SaveContact(arg1:core.ContactRecord):Promise<void>;

export function SaveLastUsername(arg1:string):Promise<void>;

export function TriggerSync():Promise<core.SyncStatus>;
