// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['core']['App']['CheckUpdate']();
}

export function DeleteContact(arg1, arg2) {
  return window['go']['core']['App']['DeleteContact'](arg1, arg2);
}

export function GetContacts(arg1) {
  return window['go']['core']['App']['GetContacts'](arg1);
}

export function PerformUpdate(arg1) {
  return window['go']['core']['App']['PerformUpdate'](arg1);
}

export function SaveContact(arg1) {
  return window['go']['core']['App']['SaveContact'](arg1);
}

export function TriggerSync() {
  return window['go']['core']['App']['TriggerSync']();
}
