// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func UpdateWizardModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"update-wizard-modal\" class=\"hidden fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md\"><div class=\"bg-[#0b1d2e] border-2 border-[#a68a56] shadow-2xl w-full max-w-lg p-6 flex flex-col gap-6\"><div class=\"flex items-center justify-between border-b border-[#a68a56]/30 pb-3\"><div class=\"flex items-center gap-3\"><div class=\"w-3 h-3 bg-[#a68a56] animate-ping\"></div><h3 class=\"text-[#a68a56] text-base font-bold uppercase tracking-widest\">System Update Available</h3></div><button id=\"close-updater-btn\" class=\"text-[#f9f8f6]/60 hover:text-[#f9f8f6] text-xs uppercase tracking-wider\">Dismiss</button></div><div id=\"updater-step-1\" class=\"flex flex-col gap-4\"><p class=\"text-xs text-[#f9f8f6]/90 leading-relaxed font-sans\">A new software version (<span id=\"update-target-version\" class=\"text-[#a68a56] font-bold\"></span>) is available on GitHub.</p><div class=\"bg-black/40 border border-[#a68a56]/20 p-3 max-h-36 overflow-y-auto font-sans\"><p class=\"text-[10px] uppercase text-[#a68a56] tracking-wider mb-1 font-bold\">Release Notes</p><div id=\"update-release-notes\" class=\"text-xs text-[#f9f8f6]/70 whitespace-pre-wrap\"></div></div><button id=\"start-update-btn\" class=\"w-full bg-[#0b1d2e] border border-[#a68a56] text-[#a68a56] hover:bg-[#a68a56] hover:text-[#0b1d2e] py-3 text-xs uppercase tracking-widest font-bold transition-colors\">Install Update & Restart</button></div><div id=\"updater-step-2\" class=\"hidden flex-col items-center justify-center py-6 gap-4\"><div class=\"w-12 h-12 border-4 border-[#a68a56] border-t-transparent rounded-full animate-spin\"></div><p class=\"text-xs text-[#a68a56] uppercase tracking-widest animate-pulse font-bold\">Downloading and applying update package...</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
